version: '3'

networks:
  supernet:

services:  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - supernet
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - supernet
  
  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - server
      - front
    volumes:
      - 'nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - supernet